name: Clone Game
on: workflow_dispatch
jobs:
  download_game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Files
        run: |
          wget -r -np -nH --cut-dirs=2 https://cdn-consumer.marketjs.com/game/idle-mining-empire/
          rm -rf .github
      - name: Config and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "All game files downloaded"
          git push
